### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by janbpunkt** [MaMaKow/dienstplan-apotheke#108]
Hey,

ich versuche, den Dienstplan bei all-inkl.com zu installieren.

Leider ist der Installer der Meinung, dass da was nicht stimmt:
```
Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /www/htdocs/w018a3fb/src/php/pages/install_page_check_requirements.php:1) in /www/htdocs/w018a3fb/src/php/classes/class.install.php on line 43

Warning: session_regenerate_id(): Cannot regenerate session id - headers already sent in /www/htdocs/w018a3fb/src/php/classes/class.install.php on line 44
This page is meant to check if:

PHP supports connections to a supported database done
Required PHP extensions are loaded done
Required PHP version done
directories (i.e. upload) are writable by the program 
Warning: Invalid argument supplied for foreach() in /www/htdocs/w018a3fb/src/php/classes/class.install.php on line 393
done

Warning: Invalid argument supplied for foreach() in /www/htdocs/w018a3fb/src/php/classes/class.install.php on line 393
```

Aktuell läuft php 7.0 (CGI)

Über Ideen freue ich mich :)
Danke.

**Comment by MaMaKow** [comment]
Moin! Ich schaue mir das heute Abend einmal an.

**Comment by MaMaKow** [comment]
Magst du mir einmal schreiben, mit welcher Version des Programmes du arbeitest?

**Comment by janbpunkt** [comment]
Moin,
ich hatte mir gestern den aktuellsten "build" gezogen.

**Comment by MaMaKow** [comment]
OK, da sind noch eine größere Menge von Fehlern enhalten.

https://github.com/MaMaKow/dienstplan-apotheke/archive/0.12.0.tar.gz sollte ohne diese Fehler sein.

Du kannst die frischen Daten auch direkt über git beziehen:

git clone https://github.com/MaMaKow/dienstplan-apotheke.git

Hat man bei all-inkl.com Zugriff auf die Konsole und auf git? Das hätte den Vorteil, dass  ich weitere Patches direkt anbieten kann. Edit: SSH Zugang scheint ab der Premium-Variante aufwärts im Angebot zu sein. Und git ist in der Liste der verfügbaren Programme: https://all-inkl.com/wichtig/anleitungen/kas/tools/ssh/verwendbare-ssh-befehle_281.html

**Comment by MaMaKow** [comment]
Ich habe mal ein PDF zusammengeschrieben:
https://github.com/MaMaKow/dienstplan-apotheke/blob/master/docs/documentation.pdf
Abschnitt 3.1.2 sollte hoffentlich mit der neuesten Version genau so funktionieren.

**Comment by p98p98** [comment]
Vielen Dank für die neue Branch, 

bei meinem Setup PHP 7.0 bzw. 7.3. kann keine Datenbankverbindung aufgebaut werden bzw. es werden keine Daten geschrieben. 

`Error while trying to create administrative user.`

>debian 9.7 
>apache 2.4.25
>MariaDB 10.1.37 stable

aus der .htaccess habe ich die php-values entfernt, weil sonst immer ein 500 Fehler kam. 

Ich kann wie unter 3.1.2. beschrieben alle Schritte durchführen, auch configs/ wird eine config_temp_install.php  erstellt, mit den Werten die ich über das Formular eingegeben habe. Verzeichnisrechte chown stimmen also. 

Welche Voraussetzungen sind notwendig um **0.12.0.** oder den aktuellen **master**  lauffähig zu bekommen? 

**_Update:_** 
ebenso eine Testinstanz bei allinkl erstellt, dort tritt gleiches auf.
Also Hoster und Berechtigung scheinen nicht die Ursache zu sein. 
Einmal root mit terminalzugriff und dann bei all inkl. Verzeichnisrechte auf 755 -R gesetzt. 


> [19-Feb-2019 10:40:54 Europe/Berlin] PHP Notice:  Undefined index: user_name in /var/www/dienstplan-apotheke-0.13.0/src/php/pages/install_page_admin.php on line 29
> [19-Feb-2019 10:40:54 Europe/Berlin] PHP Notice:  Undefined index: user_name in /var/www/dienstplan-apotheke-0.13.0/src/php/pages/install_page_admin.php on line 32
> [19-Feb-2019 10:40:54 Europe/Berlin] PHP Notice:  Undefined index: employee_id in /var/www/dienstplan-apotheke-0.13.0/src/php/pages/install_page_admin.php on line 36
> [19-Feb-2019 10:40:54 Europe/Berlin] PHP Notice:  Undefined index: email in /var/www/dienstplan-apotheke-0.13.0/src/php/pages/install_page_admin.php on line 40
> [19-Feb-2019 10:41:08 Europe/Berlin] PHP Notice:  Undefined index: user_name in /var/www/dienstplan-apotheke-0.13.0/src/php/pages/install_page_admin.php on line 29
> [19-Feb-2019 10:41:08 Europe/Berlin] PHP Notice:  Undefined index: user_name in /var/www/dienstplan-apotheke-0.13.0/src/php/pages/install_page_admin.php on line 32
> [19-Feb-2019 10:41:08 Europe/Berlin] PHP Notice:  Undefined index: employee_id in /var/www/dienstplan-apotheke-0.13.0/src/php/pages/install_page_admin.php on line 36
> [19-Feb-2019 10:41:08 Europe/Berlin] PHP Notice:  Undefined index: email in /var/www/dienstplan-apotheke-0.13.0/src/php/pages/install_page_admin.php on line 40

Danke

**Comment by MaMaKow** [comment]
Moin!

Ich versuche mir das heute Nacht einmal anzusehen und schaue, ob ich es reproduzieren kann.

**Comment by MaMaKow** [comment]
Die Warnmeldungen beziehen sich auf die Session Variable.
```$_SESSION["Config"]```
Kannst du mir die komplette ```config_temp_install.php``` (mit zensiertem Passwort) an [pdr@martin-mandelkow.de](mailto:pdr@martin-mandelkow.de) schicken? Und wenn möglich das komplette ```error.log``` mit dazu?

Email gerne auch verschlüsselt mit dem key: https://pgp.key-server.io/0xC8390DD492300239

**Comment by MaMaKow** [comment]
Ich habe auch mal einen Test auf all-ink.com gestartet. Da werde ich direkt mit einer Tirade an Warnungen begrüßt:

```
Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /www/htdocs/w01928a5/test101228.test-account.com/dienstplan-apotheke/src/php/pages/install_page_check_requirements.php:1) in /www/htdocs/w01928a5/test101228.test-account.com/dienstplan-apotheke/src/php/classes/class.install.php on line 45

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /www/htdocs/w01928a5/test101228.test-account.com/dienstplan-apotheke/src/php/pages/install_page_check_requirements.php:1) in /www/htdocs/w01928a5/test101228.test-account.com/dienstplan-apotheke/src/php/classes/class.install.php on line 45

Warning: session_regenerate_id(): Cannot regenerate session id - session is not active in /www/htdocs/w01928a5/test101228.test-account.com/dienstplan-apotheke/src/php/classes/class.install.php on line 46

Notice: Undefined index: Config in /www/htdocs/w01928a5/test101228.test-account.com/dienstplan-apotheke/src/php/classes/class.install.php on line 494

Warning: include_once(/www/htdocs/w01928a5/test101228.test-account.com/dienstplan-apotheke/config/config_temp_install.php): failed to open stream: No such file or directory in /www/htdocs/w01928a5/test101228.test-account.com/dienstplan-apotheke/src/php/classes/class.install.php on line 498

Warning: include_once(): Failed opening '/www/htdocs/w01928a5/test101228.test-account.com/dienstplan-apotheke/config/config_temp_install.php' for inclusion (include_path='.:/usr/share/php:..') in /www/htdocs/w01928a5/test101228.test-account.com/dienstplan-apotheke/src/php/classes/class.install.php on line 498

Notice: Undefined variable: config in /www/htdocs/w01928a5/test101228.test-account.com/dienstplan-apotheke/src/php/classes/class.install.php on line 499
```

Da scheint etwas bei der Speicherung von Sessiondaten komplett schief zu gehen...

**Comment by MaMaKow** [comment]
Noch viel wichtiger ist aber ein logischer Fehler bei der Erstellung der Tabellen in der Datenbank.
Wenn **keine** Datenbank existiert, so versucht das Programm eine zu erstellen. Anschließend erstellt es alle Tabellen in der Datenbank. 

Wenn aber eine Datenbank existiert, so werden die Tabellen nicht erstellt, weil das Programm davon ausgeht, dass die Datenbank bereits korrekt eingerichtet wurde. Eine vorhandene leere Datenbank bleibt also leer.

Dieses Problem lässt sich leicht durch verschieben einer einzigen Klammer lösen. Ich probiere das morgen noch mal mit einer neuen Version auf dem Hoster.

**Comment by p98p98** [comment]
Hallo und vielen Dank für deine schnelle Antwort. Ich denke das sich einige Fehlermeldungen / Warnungen auf Sessiondaten mit PHP7 beziehen. 

Mit der manuellen Installation der Datenbank lassen sich die Werte in der Tat schreiben. D.h. die Werte aus der `config_temp_install.php` werden in die `config.php` übernommen. Soweit also dann alles in Ordnung. Wäre für mich jetzt also ein gangbarer Weg mit der man. Installation der Datenbank.

Ja genau, das selbe hat mich bei all-inkl. auch erwartet, aber ebenfalls auf einer Raspi Testinstanz mit eigenem SSL-Zertifikat kommen einige Einträge in die error.log

Schönes Wochenede

**Comment by MaMaKow** [comment]
0.14.0 is out now.
https://github.com/MaMaKow/dienstplan-apotheke/releases/tag/0.14.0

@p98p98 If you are still there you might try to install this one.
