### ISSUE TITLE
Hilfe 

### ISSUE THREAD

**Issue by MarkusxX** [MaMaKow/dienstplan-apotheke#85]
Ich kann es nicht installieren Fatal error: Class 'sessions' not found /Schichtplaner/head.php on line 38

Hilfe wäre nett info@piewcom.de

**Comment by MaMaKow** [comment]
Moin!

Ich möchte Sie/Dich gerne unterstützen. 
Ich bin auch gespannt auf weitere Vorschläge zu meinem Ein-Mann-Projekt. 

An der Installationsroutine muss ich noch einiges anpassen. Viele Dinge funktionieren bisher nur durch manuellen Eingriff in die Datenbank.

Wie greifen Sie auf die Datenbank zu? Shell, phpMyAdmin oder anderes?

Welche Version haben Sie heruntergeladen? Welche Schritte haben Sie von da aus unternommen? 

Viele Grüße

**Comment by MaMaKow** [comment]
Um den Fehler auf Zeile 38 zu beheben, muss in der Datei head.php vor dieser Zeile folgende Zeile eigefügt werden:
`require_once PDR_FILE_SYSTEM_APPLICATION_PATH . 'src/php/classes/class.sessions.php';`

https://github.com/MaMaKow/dienstplan-apotheke/commit/2f628ba9a9326a85acf8d9f7044fd954a0fec0a4

**Comment by MaMaKow** [comment]
Die Datei head.php wird aber während der Installationsroutine überhaupt nicht benötigt.
Daher sollte diese Änderung nicht notwendig sein. 

Das Programm soll die Installation mit der Datei: /src/php/pages/install_page_intro.php beginnen.

Es gibt eine veraltete Datei install.php direkt im Root-Folder. Es sollte aber nichts dorthin verlinken. Die Datei existiert nur als Erinnerung an ein paar Features, die ich noch refactoren will.

**Comment by MarkusxX** [comment]
Danke für die Infos ! Ich bin selber an einem anderen System drann da ich gerne die nächsten par Tage ein Mitarbeiter System entwickeln möcht mit Schichtplan :) Wenn du/sie erreichbar sind auf anderen Platformen wie Discord, Skype oder ähnliches wäre das nett. Ich würde mich gerne ein wenig mit daran beteiligen .
